openapi: "3.0.0"
info:
  title: 'API Gateway & Function Compute'
  version: v1
'/wechat':
  get:
    x-aliyun-apigateway-request-config:
      requestProtocol: "HTTP"
      requestMode: "MAPPING"
      bodyFormat: "STREAM"
    x-aliyun-apigateway-request-parameters:
      - apiParameterName: 'encrypt_type'
      - apiParameterName: 'msg_signature'
      - apiParameterName: 'timestamp'
        location: 'Query'
        parameterType: 'String'
        required: 'REQUIRED'
      - apiParameterName: 'nonce'
        location: 'Query'
        parameterType: 'String'
      - apiParameterName: 'signature'
        location: 'Query'
        parameterType: 'String'
      - apiParameterName: 'echostr'
        location: 'Query'
        parameterType: 'String'
    x-aliyun-apigateway-fc:
      arn: acs:fc:::services/${wechat.Arn}/functions/${get.Arn}/
  post:
    x-aliyun-apigateway-request-parameters:
      - apiParameterName: 'timestamp'
        location: 'Query'
        parameterType: 'String'
        required: 'REQUIRED'
      - apiParameterName: 'nonce'
        location: 'Query'
        parameterType: 'String'
      - apiParameterName: 'signature'
        location: 'Query'
        parameterType: 'String'
      - apiParameterName: 'msg_signature'
        location: 'Query'
        parameterType: 'String'
      - apiParameterName: 'encrypt_type'
        location: 'Query'
        parameterType: 'String'
    x-aliyun-apigateway-request-config:
      requestProtocol: "HTTP"
      requestMode: "MAPPING"
      bodyFormat: "STREAM"
    x-aliyun-apigateway-fc:
      arn: acs:fc:::services/${wechat.Arn}/functions/${post.Arn}/